apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels: 
    app: reservation-app
  name: reservation-app-hpa
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reservation-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50